### PR TITLE
Switch to new middleware, bug fixes and maintenance

### LINKED ISSUE #1421: Don't depend on cors-anywhere.herokuapp.com
https://github.com/Rob--W/cors-anywhere/issues/301

### PR DESCRIPTION
**Pull request by davidyuk**
found issues:
https://github.com/aeternity/ae_mdw/issues/503
https://github.com/aeternity/ae_mdw/issues/508
https://github.com/aeternity/ae_mdw/issues/509
https://github.com/aeternity/ae_mdw/issues/510
https://github.com/aeternity/ae_mdw/issues/511
https://github.com/aeternity/ae_mdw/issues/512
https://github.com/aeternity/aeternity/issues/3852
https://github.com/aeternity/superhero-wallet/issues/1400
https://github.com/aeternity/mdw-frontend/issues/162
https://github.com/aeternity/aepp-base/issues/1436
https://github.com/aeternity/aepp-base/issues/1437

closes #1421

### CODE REVIEW

File: src/pages/aens/NameList.vue [hunk 1]
```diff
@@ -27,13 +27,14 @@
...
           v-for="bid in owned.bids"
-          :key="bid.transaction.hash"
-          :name="bid.nameAuctionEntry.name"
-          :balance="bid.transaction.tx.nameFee"
-          :address="bid.transaction.tx.accountId"
-          :to="{ name: 'auction-details', params: { name: bid.nameAuctionEntry.name } }"
+          :key="bid.name"
+          :name="bid.name"
+          :balance="bid.nameFee"
+          :address="(bid.auction ?? bid.info).lastBid.tx.accountId"
```
Comment (CedrikNikita) [inline src/pages/aens/NameList.vue:36]: https://github.com/vuejs/vue/issues/11088

File: package.json [hunk 2]
```diff
@@ -11,94 +11,80 @@
...
     "test": "npm run lint && npm run test:unit && npm run test:e2e -- --headless",
-    "storybook:build": "vue-cli-service storybook:build -c config/storybook",
-    "storybook:serve": "vue-cli-service storybook:serve -p 6006 -c config/storybook",
     "test:e2e": "vue-cli-service test:e2e",
     "test:unit": "vue-cli-service test:unit",
     "i18n:report": "vue-i18n-extract report --vueFiles './src/**/*.?(js|vue)' --languageFiles './src/locales/**/*.json'"
   },
   "dependencies": {
-    "@aeternity/aepp-sdk": "^8.1.0",
+    "@aeternity/aepp-sdk": "github:aeternity/aepp-sdk-js#develop",
```
Comment (CedrikNikita) [inline package.json:22]: I don't like an idea to depend from the develop branch.
Also the installed package from the develop branch doesnt have a lot of prebuild files inside `es` folder.

Comment (davidyuk) [reply package.json:22]: this is not compatible with Windows, but it is the fastest way to make a release of Base aepp 🙃
