### PR TITLE
Fix showing of message about restricting access to camera

### LINKED ISSUE #805: iOS: Show a message explaining that user needs to enable camera access to Chrome in their settings, when they have already selected No
Right now the page shows a blank screen

### PR DESCRIPTION
**Pull request by etharner**
In iOS Safari and Chrome.
Closes #805

### CODE REVIEW

File: src/components/QrCodeReader.vue [hunk 1]
```diff
@@ -57,6 +58,14 @@ export default {
       return;
     }
 
+    if (process.env.IS_IOS) {
+      try {
+        await navigator.mediaDevices.getUserMedia({ video: true });
```
Comment (davidyuk) [inline src/components/QrCodeReader.vue]: Shouldn't you assign something to `cameraAllowed`?

**Comment by etharner** [comment]
It looks like Chrome on iOS doesn't support WebRTC, so we will see the message but can't grant access anyway. But it works in Safari.
https://stackoverflow.com/a/29164511
